services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto para comunicación con RabbitMQ
      - "15672:15672" # Puerto para el panel de administración web
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 10s

  warehouse-service:
    build: ./warehouse-service
    ports:
      - "3344:3344/udp"
      - "3355:3355/udp"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    # If you need to connect to other services like databases
    # networks:
    #   - app-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

    depends_on:
      - rabbitmq

  monitoring-service:
    build: ./monitoring-service
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    # If you need to connect to other services like databases
    # networks:
    #   - app-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

    depends_on:
      - rabbitmq
      - warehouse-service
