services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto para comunicación con RabbitMQ
      - "15672:15672" # Puerto para el panel de administración web
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 10s

  # udp-service:
  #   build: .  
  #   container_name: udp-service
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     UDP_PORT: 9999
  #     RABBITMQ_HOST: rabbitmq
  #     RABBITMQ_QUEUE: udp_messages
  #     RABBITMQ_USER: user
  #     RABBITMQ_PASS: password
  #   ports:
  #     - "9999:9999/udp"
